#!/bin/sh

#oformat=$(file -b $1)
#iformat=$(file -b $2)

oformat=$(echo $1 | sed "s|.*\.\(.*\)|\1|" | tr '[:upper:] [:lower:]')
iformat=$(echo $2 | sed "s|.*\.\(.*\)|\1|" | tr '[:upper:] [:lower:]')

FindBestPath(){
	if [ "$a" = "$1" ]
	then
		return false
	fi

	IFS=$'\n'
	for a in $(cat $3)
	do
		print $a
		b=$(echo $a | sed "s|\(.*\)\t.*\t.*|\1|")
		c=$(echo $a | sed "s|.*\t\(.*\)\t.*|\1|")
		d=$(echo $a | sed "s|.*\t.*\t\(.*\)|\1|")

		if $c=$1
		then
			f=$(FindBestPath $b $c $3)
			if $f
			then
				return $(echo $d | sed "s|\$1|$1|" | sed "s|\$2|$2|") $f
			else
				return $
			fi
		fi
	done
}

commands=()

while true
do
	e=$(FindBestPath $iformat $oformat ./conversions)
	if ! $e
	then
		break
	else
		commands[${#commands[*]}]=$e
	fi
done

for command in commands
do
	exec $command
done
